export type { CoChangePatternRow } from '../types.js';
export {
  CoChangeAggregator,
  type CoChangeCacheJobResult,
  classifyChangedPaths,
  fingerprintKbPaths,
  kbSourcePathSetForApprovedDocs,
  normalizeGitPath,
  parseCommitFileLog,
  pathsRepoRelativeToProject,
  type RunCoChangeCacheJobOptions,
  runCoChangeCacheJob,
} from './co-change-cache.js';
export {
  aggregateRefactorSignals,
  buildSplitCandidatePayload,
  cohortMedianGapRateForKind,
  DEFAULT_REFACTOR_TRIGGER,
  DOC_REFACTOR_ALGORITHM_VERSION,
  type DocRefactorAggregate,
  effectiveGapRateThreshold,
  finiteMedian,
  gapRate,
  type RefactorTrigger,
  shouldEmitSplitCandidate,
} from './doc-refactor.js';
export {
  buildCoverageOptimizationContext,
  buildMissClustersFromObservations,
  buildPathClustersFromFiles,
  derivePathPattern,
  loadCoChangePatterns,
  type MissCluster,
  type PathCluster,
} from './edge-candidate-builder.js';
export {
  deterministicPathProbesForGlob,
  type EdgeValidationImpact,
  type EdgeValidationResult,
  isCanonicalDirTreeGlob,
  pathGlobSubsumes,
  type ValidatePathRequiresEdgeInput,
  validatePathRequiresEdge,
} from './edge-validation.js';
export {
  type AnalyzeImportPlanOptions,
  analyzeDocumentForImportPlan,
  analyzeImportBatch,
  type BatchImportPlan,
  type CoverageDelta,
  type CrossDocOverlap,
  extractPathLikeStrings,
  IMPORT_PLAN_ALGORITHM_VERSION,
  type ImportPlan,
  jaccardSimilarity,
  type OverlapWarning,
  parseBatchImportPlanJson,
  parseImportPlanJson,
  type SuggestedImportUnit,
  splitMarkdownSections,
} from './import-plan.js';
export {
  collectSemanticStalenessFindings,
  extractTsExportedSymbols,
  findRenameCandidatePath,
  fingerprintEdgeLinkedArtifacts,
  linkedPathsForDoc,
  listRepoRelativeFiles,
  SEMANTIC_STALENESS_ALGORITHM_VERSION,
  type SemanticStalenessScanInput,
  type SemanticStalenessScanResult,
  stableStringifyFingerprints,
} from './staleness.js';
